[package]
name = "meta"
version = "0.1.0"
authors = ["baturalp"]
edition = "2021"
publish = false

[dev-dependencies]
escrow-contract = {path = ".."}

[dependencies.multiversx-sc-meta]
version = "0.55.0"